// Code generated by ent, DO NOT EDIT.
package admin

import (
	"time"

	"github.com/occult/pagode/ent/form"
	"github.com/occult/pagode/ent/job"
	"github.com/occult/pagode/ent/paymentintent"
	"github.com/occult/pagode/ent/paymentmethod"
	"github.com/occult/pagode/ent/question"
	"github.com/occult/pagode/ent/subscription"
	"github.com/occult/pagode/ent/user"
)

type Answer struct {
	Value     string     `form:"value"`
	CreatedAt *time.Time `form:"created_at"`
}

type Form struct {
	Title       string            `form:"title"`
	Description *string           `form:"description"`
	Published   bool              `form:"published"`
	Slug        string            `form:"slug"`
	DisplayMode *form.DisplayMode `form:"display_mode"`
	UserID      int               `form:"user_id"`
	CreatedAt   *time.Time        `form:"created_at"`
	UpdatedAt   *time.Time        `form:"updated_at"`
}

type Job struct {
	Queue       string                 `form:"queue"`
	Payload     map[string]interface{} `form:"payload"`
	Attempts    *int                   `form:"attempts"`
	MaxAttempts *int                   `form:"max_attempts"`
	Status      *job.Status            `form:"status"`
	Error       *string                `form:"error"`
	CreatedAt   *time.Time             `form:"created_at"`
	ProcessedAt *time.Time             `form:"processed_at"`
}

type PasswordToken struct {
	Token     *string    `form:"token"`
	UserID    int        `form:"user_id"`
	CreatedAt *time.Time `form:"created_at"`
}

type PaymentCustomer struct {
	ProviderCustomerID string                  `form:"provider_customer_id"`
	Provider           *string                 `form:"provider"`
	Email              string                  `form:"email"`
	Name               *string                 `form:"name"`
	Metadata           *map[string]interface{} `form:"metadata"`
	CreatedAt          *time.Time              `form:"created_at"`
	UpdatedAt          *time.Time              `form:"updated_at"`
}

type PaymentIntent struct {
	ProviderPaymentIntentID string                  `form:"provider_payment_intent_id"`
	Provider                *string                 `form:"provider"`
	Status                  *paymentintent.Status   `form:"status"`
	Amount                  int64                   `form:"amount"`
	Currency                *string                 `form:"currency"`
	Description             *string                 `form:"description"`
	ClientSecret            *string                 `form:"client_secret"`
	Metadata                *map[string]interface{} `form:"metadata"`
	CreatedAt               *time.Time              `form:"created_at"`
	UpdatedAt               *time.Time              `form:"updated_at"`
}

type PaymentMethod struct {
	ProviderPaymentMethodID string                  `form:"provider_payment_method_id"`
	Provider                *string                 `form:"provider"`
	Type                    *paymentmethod.Type     `form:"type"`
	LastFour                *string                 `form:"last_four"`
	Brand                   *string                 `form:"brand"`
	ExpMonth                *int                    `form:"exp_month"`
	ExpYear                 *int                    `form:"exp_year"`
	IsDefault               bool                    `form:"is_default"`
	Metadata                *map[string]interface{} `form:"metadata"`
	CreatedAt               *time.Time              `form:"created_at"`
	UpdatedAt               *time.Time              `form:"updated_at"`
}

type Question struct {
	Type        *question.Type          `form:"type"`
	Title       string                  `form:"title"`
	Description *string                 `form:"description"`
	Placeholder *string                 `form:"placeholder"`
	Required    bool                    `form:"required"`
	Order       *int                    `form:"order"`
	Options     *map[string]interface{} `form:"options"`
	Validation  *map[string]interface{} `form:"validation"`
	CreatedAt   *time.Time              `form:"created_at"`
	UpdatedAt   *time.Time              `form:"updated_at"`
}

type Response struct {
	SubmittedAt *time.Time `form:"submitted_at"`
	Completed   bool       `form:"completed"`
	IPAddress   *string    `form:"IPAddress"`
	UserAgent   *string    `form:"UserAgent"`
}

type Subscription struct {
	ProviderSubscriptionID string                  `form:"provider_subscription_id"`
	Provider               *string                 `form:"provider"`
	Status                 *subscription.Status    `form:"status"`
	PriceID                string                  `form:"price_id"`
	Amount                 int64                   `form:"amount"`
	Currency               *string                 `form:"currency"`
	Interval               subscription.Interval   `form:"interval"`
	IntervalCount          *int                    `form:"interval_count"`
	CurrentPeriodStart     *time.Time              `form:"current_period_start"`
	CurrentPeriodEnd       *time.Time              `form:"current_period_end"`
	TrialStart             *time.Time              `form:"trial_start"`
	TrialEnd               *time.Time              `form:"trial_end"`
	CanceledAt             *time.Time              `form:"canceled_at"`
	EndedAt                *time.Time              `form:"ended_at"`
	Metadata               *map[string]interface{} `form:"metadata"`
	CreatedAt              *time.Time              `form:"created_at"`
	UpdatedAt              *time.Time              `form:"updated_at"`
}

type User struct {
	Name                 string                  `form:"name"`
	Email                string                  `form:"email"`
	Password             *string                 `form:"password"`
	Username             *string                 `form:"username"`
	CompanyName          *string                 `form:"company_name"`
	Verified             bool                    `form:"verified"`
	Admin                bool                    `form:"admin"`
	Website              *string                 `form:"website"`
	BrandButtonColor     *string                 `form:"brand_button_color"`
	BrandBackgroundColor *string                 `form:"brand_background_color"`
	BrandTextColor       *string                 `form:"brand_text_color"`
	BrandColorsStatus    *user.BrandColorsStatus `form:"brand_colors_status"`
	Logo                 *string                 `form:"logo"`
	Language             *user.Language          `form:"language"`
	CreatedAt            *time.Time              `form:"created_at"`
}

type EntityList struct {
	Columns     []string
	Entities    []EntityValues
	Page        int
	HasNextPage bool
}

type EntityValues struct {
	ID     int
	Values []string
}

type HandlerConfig struct {
	ItemsPerPage int
	PageQueryKey string
	TimeFormat   string
}

func GetEntityTypeNames() []string {
	return []string{
		"Answer",
		"Form",
		"Job",
		"PasswordToken",
		"PaymentCustomer",
		"PaymentIntent",
		"PaymentMethod",
		"Question",
		"Response",
		"Subscription",
		"User",
	}
}
