// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/form"
	"github.com/occult/pagode/ent/question"
	"github.com/occult/pagode/ent/response"
	"github.com/occult/pagode/ent/user"
)

// FormCreate is the builder for creating a Form entity.
type FormCreate struct {
	config
	mutation *FormMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (fc *FormCreate) SetTitle(s string) *FormCreate {
	fc.mutation.SetTitle(s)
	return fc
}

// SetDescription sets the "description" field.
func (fc *FormCreate) SetDescription(s string) *FormCreate {
	fc.mutation.SetDescription(s)
	return fc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (fc *FormCreate) SetNillableDescription(s *string) *FormCreate {
	if s != nil {
		fc.SetDescription(*s)
	}
	return fc
}

// SetPublished sets the "published" field.
func (fc *FormCreate) SetPublished(b bool) *FormCreate {
	fc.mutation.SetPublished(b)
	return fc
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (fc *FormCreate) SetNillablePublished(b *bool) *FormCreate {
	if b != nil {
		fc.SetPublished(*b)
	}
	return fc
}

// SetSlug sets the "slug" field.
func (fc *FormCreate) SetSlug(s string) *FormCreate {
	fc.mutation.SetSlug(s)
	return fc
}

// SetDisplayMode sets the "display_mode" field.
func (fc *FormCreate) SetDisplayMode(fm form.DisplayMode) *FormCreate {
	fc.mutation.SetDisplayMode(fm)
	return fc
}

// SetNillableDisplayMode sets the "display_mode" field if the given value is not nil.
func (fc *FormCreate) SetNillableDisplayMode(fm *form.DisplayMode) *FormCreate {
	if fm != nil {
		fc.SetDisplayMode(*fm)
	}
	return fc
}

// SetUserID sets the "user_id" field.
func (fc *FormCreate) SetUserID(i int) *FormCreate {
	fc.mutation.SetUserID(i)
	return fc
}

// SetCreatedAt sets the "created_at" field.
func (fc *FormCreate) SetCreatedAt(t time.Time) *FormCreate {
	fc.mutation.SetCreatedAt(t)
	return fc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fc *FormCreate) SetNillableCreatedAt(t *time.Time) *FormCreate {
	if t != nil {
		fc.SetCreatedAt(*t)
	}
	return fc
}

// SetUpdatedAt sets the "updated_at" field.
func (fc *FormCreate) SetUpdatedAt(t time.Time) *FormCreate {
	fc.mutation.SetUpdatedAt(t)
	return fc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fc *FormCreate) SetNillableUpdatedAt(t *time.Time) *FormCreate {
	if t != nil {
		fc.SetUpdatedAt(*t)
	}
	return fc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (fc *FormCreate) SetOwnerID(id int) *FormCreate {
	fc.mutation.SetOwnerID(id)
	return fc
}

// SetOwner sets the "owner" edge to the User entity.
func (fc *FormCreate) SetOwner(u *User) *FormCreate {
	return fc.SetOwnerID(u.ID)
}

// AddQuestionIDs adds the "questions" edge to the Question entity by IDs.
func (fc *FormCreate) AddQuestionIDs(ids ...int) *FormCreate {
	fc.mutation.AddQuestionIDs(ids...)
	return fc
}

// AddQuestions adds the "questions" edges to the Question entity.
func (fc *FormCreate) AddQuestions(q ...*Question) *FormCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return fc.AddQuestionIDs(ids...)
}

// AddResponseIDs adds the "responses" edge to the Response entity by IDs.
func (fc *FormCreate) AddResponseIDs(ids ...int) *FormCreate {
	fc.mutation.AddResponseIDs(ids...)
	return fc
}

// AddResponses adds the "responses" edges to the Response entity.
func (fc *FormCreate) AddResponses(r ...*Response) *FormCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return fc.AddResponseIDs(ids...)
}

// Mutation returns the FormMutation object of the builder.
func (fc *FormCreate) Mutation() *FormMutation {
	return fc.mutation
}

// Save creates the Form in the database.
func (fc *FormCreate) Save(ctx context.Context) (*Form, error) {
	fc.defaults()
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FormCreate) SaveX(ctx context.Context) *Form {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FormCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FormCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FormCreate) defaults() {
	if _, ok := fc.mutation.Published(); !ok {
		v := form.DefaultPublished
		fc.mutation.SetPublished(v)
	}
	if _, ok := fc.mutation.DisplayMode(); !ok {
		v := form.DefaultDisplayMode
		fc.mutation.SetDisplayMode(v)
	}
	if _, ok := fc.mutation.CreatedAt(); !ok {
		v := form.DefaultCreatedAt()
		fc.mutation.SetCreatedAt(v)
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		v := form.DefaultUpdatedAt()
		fc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FormCreate) check() error {
	if _, ok := fc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Form.title"`)}
	}
	if v, ok := fc.mutation.Title(); ok {
		if err := form.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Form.title": %w`, err)}
		}
	}
	if _, ok := fc.mutation.Published(); !ok {
		return &ValidationError{Name: "published", err: errors.New(`ent: missing required field "Form.published"`)}
	}
	if _, ok := fc.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Form.slug"`)}
	}
	if v, ok := fc.mutation.Slug(); ok {
		if err := form.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Form.slug": %w`, err)}
		}
	}
	if _, ok := fc.mutation.DisplayMode(); !ok {
		return &ValidationError{Name: "display_mode", err: errors.New(`ent: missing required field "Form.display_mode"`)}
	}
	if v, ok := fc.mutation.DisplayMode(); ok {
		if err := form.DisplayModeValidator(v); err != nil {
			return &ValidationError{Name: "display_mode", err: fmt.Errorf(`ent: validator failed for field "Form.display_mode": %w`, err)}
		}
	}
	if _, ok := fc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Form.user_id"`)}
	}
	if _, ok := fc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Form.created_at"`)}
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Form.updated_at"`)}
	}
	if len(fc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Form.owner"`)}
	}
	return nil
}

func (fc *FormCreate) sqlSave(ctx context.Context) (*Form, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FormCreate) createSpec() (*Form, *sqlgraph.CreateSpec) {
	var (
		_node = &Form{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(form.Table, sqlgraph.NewFieldSpec(form.FieldID, field.TypeInt))
	)
	if value, ok := fc.mutation.Title(); ok {
		_spec.SetField(form.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := fc.mutation.Description(); ok {
		_spec.SetField(form.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := fc.mutation.Published(); ok {
		_spec.SetField(form.FieldPublished, field.TypeBool, value)
		_node.Published = value
	}
	if value, ok := fc.mutation.Slug(); ok {
		_spec.SetField(form.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := fc.mutation.DisplayMode(); ok {
		_spec.SetField(form.FieldDisplayMode, field.TypeEnum, value)
		_node.DisplayMode = value
	}
	if value, ok := fc.mutation.CreatedAt(); ok {
		_spec.SetField(form.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fc.mutation.UpdatedAt(); ok {
		_spec.SetField(form.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := fc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   form.OwnerTable,
			Columns: []string{form.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   form.QuestionsTable,
			Columns: []string{form.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   form.ResponsesTable,
			Columns: []string{form.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FormCreateBulk is the builder for creating many Form entities in bulk.
type FormCreateBulk struct {
	config
	err      error
	builders []*FormCreate
}

// Save creates the Form entities in the database.
func (fcb *FormCreateBulk) Save(ctx context.Context) ([]*Form, error) {
	if fcb.err != nil {
		return nil, fcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Form, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FormMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FormCreateBulk) SaveX(ctx context.Context) []*Form {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FormCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FormCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
