// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/job"
	"github.com/occult/pagode/ent/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (ju *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetQueue sets the "queue" field.
func (ju *JobUpdate) SetQueue(s string) *JobUpdate {
	ju.mutation.SetQueue(s)
	return ju
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (ju *JobUpdate) SetNillableQueue(s *string) *JobUpdate {
	if s != nil {
		ju.SetQueue(*s)
	}
	return ju
}

// SetPayload sets the "payload" field.
func (ju *JobUpdate) SetPayload(m map[string]interface{}) *JobUpdate {
	ju.mutation.SetPayload(m)
	return ju
}

// SetAttempts sets the "attempts" field.
func (ju *JobUpdate) SetAttempts(i int) *JobUpdate {
	ju.mutation.ResetAttempts()
	ju.mutation.SetAttempts(i)
	return ju
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (ju *JobUpdate) SetNillableAttempts(i *int) *JobUpdate {
	if i != nil {
		ju.SetAttempts(*i)
	}
	return ju
}

// AddAttempts adds i to the "attempts" field.
func (ju *JobUpdate) AddAttempts(i int) *JobUpdate {
	ju.mutation.AddAttempts(i)
	return ju
}

// SetMaxAttempts sets the "max_attempts" field.
func (ju *JobUpdate) SetMaxAttempts(i int) *JobUpdate {
	ju.mutation.ResetMaxAttempts()
	ju.mutation.SetMaxAttempts(i)
	return ju
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (ju *JobUpdate) SetNillableMaxAttempts(i *int) *JobUpdate {
	if i != nil {
		ju.SetMaxAttempts(*i)
	}
	return ju
}

// AddMaxAttempts adds i to the "max_attempts" field.
func (ju *JobUpdate) AddMaxAttempts(i int) *JobUpdate {
	ju.mutation.AddMaxAttempts(i)
	return ju
}

// SetStatus sets the "status" field.
func (ju *JobUpdate) SetStatus(j job.Status) *JobUpdate {
	ju.mutation.SetStatus(j)
	return ju
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ju *JobUpdate) SetNillableStatus(j *job.Status) *JobUpdate {
	if j != nil {
		ju.SetStatus(*j)
	}
	return ju
}

// SetError sets the "error" field.
func (ju *JobUpdate) SetError(s string) *JobUpdate {
	ju.mutation.SetError(s)
	return ju
}

// SetNillableError sets the "error" field if the given value is not nil.
func (ju *JobUpdate) SetNillableError(s *string) *JobUpdate {
	if s != nil {
		ju.SetError(*s)
	}
	return ju
}

// ClearError clears the value of the "error" field.
func (ju *JobUpdate) ClearError() *JobUpdate {
	ju.mutation.ClearError()
	return ju
}

// SetProcessedAt sets the "processed_at" field.
func (ju *JobUpdate) SetProcessedAt(t time.Time) *JobUpdate {
	ju.mutation.SetProcessedAt(t)
	return ju
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (ju *JobUpdate) SetNillableProcessedAt(t *time.Time) *JobUpdate {
	if t != nil {
		ju.SetProcessedAt(*t)
	}
	return ju
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (ju *JobUpdate) ClearProcessedAt() *JobUpdate {
	ju.mutation.ClearProcessedAt()
	return ju
}

// Mutation returns the JobMutation object of the builder.
func (ju *JobUpdate) Mutation() *JobMutation {
	return ju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ju.sqlSave, ju.mutation, ju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JobUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JobUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ju *JobUpdate) check() error {
	if v, ok := ju.mutation.Queue(); ok {
		if err := job.QueueValidator(v); err != nil {
			return &ValidationError{Name: "queue", err: fmt.Errorf(`ent: validator failed for field "Job.queue": %w`, err)}
		}
	}
	if v, ok := ju.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (ju *JobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ju.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.Queue(); ok {
		_spec.SetField(job.FieldQueue, field.TypeString, value)
	}
	if value, ok := ju.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := ju.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := ju.mutation.MaxAttempts(); ok {
		_spec.SetField(job.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(job.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := ju.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ju.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
	}
	if ju.mutation.ErrorCleared() {
		_spec.ClearField(job.FieldError, field.TypeString)
	}
	if value, ok := ju.mutation.ProcessedAt(); ok {
		_spec.SetField(job.FieldProcessedAt, field.TypeTime, value)
	}
	if ju.mutation.ProcessedAtCleared() {
		_spec.ClearField(job.FieldProcessedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ju.mutation.done = true
	return n, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetQueue sets the "queue" field.
func (juo *JobUpdateOne) SetQueue(s string) *JobUpdateOne {
	juo.mutation.SetQueue(s)
	return juo
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableQueue(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetQueue(*s)
	}
	return juo
}

// SetPayload sets the "payload" field.
func (juo *JobUpdateOne) SetPayload(m map[string]interface{}) *JobUpdateOne {
	juo.mutation.SetPayload(m)
	return juo
}

// SetAttempts sets the "attempts" field.
func (juo *JobUpdateOne) SetAttempts(i int) *JobUpdateOne {
	juo.mutation.ResetAttempts()
	juo.mutation.SetAttempts(i)
	return juo
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableAttempts(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetAttempts(*i)
	}
	return juo
}

// AddAttempts adds i to the "attempts" field.
func (juo *JobUpdateOne) AddAttempts(i int) *JobUpdateOne {
	juo.mutation.AddAttempts(i)
	return juo
}

// SetMaxAttempts sets the "max_attempts" field.
func (juo *JobUpdateOne) SetMaxAttempts(i int) *JobUpdateOne {
	juo.mutation.ResetMaxAttempts()
	juo.mutation.SetMaxAttempts(i)
	return juo
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableMaxAttempts(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetMaxAttempts(*i)
	}
	return juo
}

// AddMaxAttempts adds i to the "max_attempts" field.
func (juo *JobUpdateOne) AddMaxAttempts(i int) *JobUpdateOne {
	juo.mutation.AddMaxAttempts(i)
	return juo
}

// SetStatus sets the "status" field.
func (juo *JobUpdateOne) SetStatus(j job.Status) *JobUpdateOne {
	juo.mutation.SetStatus(j)
	return juo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableStatus(j *job.Status) *JobUpdateOne {
	if j != nil {
		juo.SetStatus(*j)
	}
	return juo
}

// SetError sets the "error" field.
func (juo *JobUpdateOne) SetError(s string) *JobUpdateOne {
	juo.mutation.SetError(s)
	return juo
}

// SetNillableError sets the "error" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableError(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetError(*s)
	}
	return juo
}

// ClearError clears the value of the "error" field.
func (juo *JobUpdateOne) ClearError() *JobUpdateOne {
	juo.mutation.ClearError()
	return juo
}

// SetProcessedAt sets the "processed_at" field.
func (juo *JobUpdateOne) SetProcessedAt(t time.Time) *JobUpdateOne {
	juo.mutation.SetProcessedAt(t)
	return juo
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableProcessedAt(t *time.Time) *JobUpdateOne {
	if t != nil {
		juo.SetProcessedAt(*t)
	}
	return juo
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (juo *JobUpdateOne) ClearProcessedAt() *JobUpdateOne {
	juo.mutation.ClearProcessedAt()
	return juo
}

// Mutation returns the JobMutation object of the builder.
func (juo *JobUpdateOne) Mutation() *JobMutation {
	return juo.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (juo *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	juo.mutation.Where(ps...)
	return juo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Job entity.
func (juo *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, juo.sqlSave, juo.mutation, juo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JobUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (juo *JobUpdateOne) check() error {
	if v, ok := juo.mutation.Queue(); ok {
		if err := job.QueueValidator(v); err != nil {
			return &ValidationError{Name: "queue", err: fmt.Errorf(`ent: validator failed for field "Job.queue": %w`, err)}
		}
	}
	if v, ok := juo.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (juo *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := juo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.Queue(); ok {
		_spec.SetField(job.FieldQueue, field.TypeString, value)
	}
	if value, ok := juo.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := juo.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := juo.mutation.MaxAttempts(); ok {
		_spec.SetField(job.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(job.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := juo.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := juo.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
	}
	if juo.mutation.ErrorCleared() {
		_spec.ClearField(job.FieldError, field.TypeString)
	}
	if value, ok := juo.mutation.ProcessedAt(); ok {
		_spec.SetField(job.FieldProcessedAt, field.TypeTime, value)
	}
	if juo.mutation.ProcessedAtCleared() {
		_spec.ClearField(job.FieldProcessedAt, field.TypeTime)
	}
	_node = &Job{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	juo.mutation.done = true
	return _node, nil
}
