// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// PaymentCustomer is the predicate function for paymentcustomer builders.
type PaymentCustomer func(*sql.Selector)

// PaymentIntent is the predicate function for paymentintent builders.
type PaymentIntent func(*sql.Selector)

// PaymentMethod is the predicate function for paymentmethod builders.
type PaymentMethod func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
